name: Django CI/CD to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          set -e
    
          cd /home/ubuntu/django-docker
          git pull origin main
          echo "${{ secrets.ENV_FILE }}" > .env
    
          sudo docker stop django-docker || true
          sudo docker rm django-docker || true
    
          sudo docker build -t django-docker .
    
          # Run database migrations inside a temporary container
          sudo docker run --rm --env-file .env django-docker python manage.py migrate
    
          # Start the container with web server
          sudo docker run -d --restart always --env-file .env -p 8000:8000 --name django-docker django-docker
        EOF